name: Sync Demo
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: executing remote ssh commands 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        envs: GITHUB_REF
        script: |
          cd *_test_dir/
          cd histonedb
          git stash
          git pull
          echo Checking out to branch ${GITHUB_REF##*/}
          git checkout ${GITHUB_REF##*/}
          git pull
          git stash pop
